collections:
  - name: community.general
    version: 10.0.1
  - name: fedora.linux_system_roles
    version: 1.90.3

roles:
  - name: haxorof.docker_ce
    version: 6.1.0
  - name: cchurch.virtualenv
    version: 0.6.5
  - name: geerlingguy.repo-epel
    version: 3.1.1
