---
# file: setup.yml
- name: Base configuration
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather subset of facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
      become: false
      tags:
        - facts

    - name: Preflight check for RHEL systems only
      ansible.builtin.assert:
        that:
          - org_id is defined
          - activationkey is defined
        fail_msg: >
          You need to specify org_id and activationkey as inventory variables
          for RHEL machines
        success_msg: Both org_id and activationkey defined, continuing...
      when: ansible_distribution == "RedHat"

    - name: Register with Red Hat if required
      community.general.redhat_subscription:
        activationkey: "{{ activationkey }}"
        org_id: "{{ org_id }}"
        state: present
      when: ansible_distribution == "RedHat"

    - name: Copy over requirements.txt
      ansible.builtin.copy:
        src: requirements.txt
        dest: "{{ ansible_user_dir }}/requirements.txt"
        owner: "{{ ansible_user_id }}"
        mode: "0644"
      become: false
      tags:
        - pip

    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Install python3-dnf5 if needed
      ansible.builtin.command:
        dnf -y install python3-libdnf5
      when: ansible_pkg_mgr == "dnf5"
      changed_when: false

    - name: Install EPEL on RHEL machine
      ansible.builtin.include_role:
        name: geerlingguy.repo-epel
      when:
        - ansible_distribution == "RedHat"

    - name: Set crb repository name
      ansible.builtin.set_fact:
        crb_repo_name: "{{ 'codeready-builder-for-rhel-' +
                   ansible_distribution_major_version|string +
                   '-' +
                   ansible_architecture +
                   '-rpms' }}"

    - name: Enable codeready-builder for RHEL
      community.general.rhsm_repository:
        name: "{{ crb_repo_name }}"
      when: ansible_distribution == 'RedHat'

    - name: Install base packages for Fedora
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: installed
      loop:
        - direnv
        - git
        - mc
        - vim-enhanced
        - python3
        - python3-virtualenvwrapper
        - glibc-langpack-en
        - glibc-langpack-nl
        - wget2
      when:
        - "item not in ansible_facts.packages"
        - ansible_distribution == "Fedora"
      tags:
        - packages

    - name: Install base packages for RHEL
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: installed
      loop:
        - git
        - mc
        - vim-enhanced
        - python3
        - python3-virtualenv
        - glibc-langpack-en
        - glibc-langpack-nl
        - python3.12
        - wget
      when:
        - "item not in ansible_facts.packages"
        - ansible_distribution == "RedHat"
      tags:
        - packages

    - name: Remove unwanted packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - podman
        - buildah
        - skopeo
      when: "item in ansible_facts.packages"
      tags:
        - packages

  roles:
    - role: fedora.linux_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: time.kpn.net
      tags:
        - sysconfig

    - role: haxorof.docker_ce
      tags:
        - packages

    - role: cchurch.virtualenv
      vars:
        virtualenv_user: "{{ ansible_user_id }}"
        virtualenv_path: "{{ ansible_user_dir }}/.virtualenvs/ansible"
        virtualenv_requirements: "{{ ansible_user_dir }}/requirements.txt"
        virtualenv_python: "{{ python_path | default(omit) }}"
      become: false
      tags:
        - pip

  post_tasks:
    - name: Add my user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
      notify:
        - Reboot machine
      tags:
        - user

    - name: Create Rosetta binfmt configuration file
      ansible.builtin.copy:
        src: files/rosetta.conf
        dest: /usr/lib/binfmt.d/rosetta.conf
        owner: root
        group: root
        mode: "0644"
      tags:
        - binfmt

    - name: Copy over Rosetta SELinux module
      ansible.builtin.copy:
        src: "{{ lookup('first_found', selinux_te_files) }}"
        dest: /root/rosetta.te
        owner: root
        group: root
        mode: "0644"
      vars:
        selinux_te_files:
          - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}/rosetta.te"
          - "{{ ansible_distribution }}/rosetta.te"
          - "{{ ansible_os_family }}/rosetta.te"
      tags:
        - binfmt
        - selinux

    - name: Convert SELinux type enforcement file to policy file
      ansible.builtin.command:
        cmd: checkmodule -M -m -o /root/rosetta.mod /root/rosetta.te
        creates: /root/rosetta.mod
      tags:
        - selinux

    - name: Compile SELinux policy file to policy package
      ansible.builtin.command:
        cmd: semodule_package -o /root/rosetta.pp -m /root/rosetta.mod
        creates: /root/rosetta.pp
      tags:
        - selinux

    - name: Check loaded SELinux modules
      ansible.builtin.command:
        cmd: semodule -l
      register: selinux_modules
      changed_when: false
      tags:
        - selinux

    - name: Load Rosetta SELinux module
      ansible.builtin.command:
        cmd: semodule -i /root/rosetta.pp
      when: "'rosetta' not in selinux_modules.stdout"
      changed_when: "'rosetta' not in selinux_modules.stdout"
      tags:
        - selinux

    - name: Create systemd-binfmt.service.d directory
      ansible.builtin.file:
        path: /etc/systemd/system/systemd-binfmt.service.d/
        state: directory
        owner: root
        group: root
        mode: "0755"
      tags:
        - binfmt

    - name: Copy systemd-binfmt.service drop-in
      ansible.builtin.copy:
        src: systemd-binfmt.override.service
        dest: /etc/systemd/system/systemd-binfmt.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Reload systemd
      tags:
        - binfmt

    - name: Enable systemd-binfmt
      ansible.builtin.service:
        name: systemd-binfmt
        enabled: true
      tags:
        - binfmt

  handlers:
    - name: Reboot machine
      ansible.builtin.reboot:

    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true
